import { useEffect, useState, type FormEvent } from 'react'
import { FolderUp, ImagePlus, Plus, RefreshCw, RotateCcw, Trash2 } from 'lucide-react'

type Category = { name: string; description?: string }
type DeveloperState = { categories: Category[]; background: string; backgrounds: string[]; articleCount: number; siteTitle: string; siteDescription: string }

async function post(action: string, body: Record<string, unknown> = {}) {
  const response = await fetch(`/__developer/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
  const result = await response.json() as { error?: string }
  if (!response.ok) throw new Error(result.error ?? 'Developer action failed.')
  return result
}

function fileBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(reader.error); reader.onload = () => resolve(String(reader.result).split(',')[1] ?? ''); reader.readAsDataURL(file) })
}

export default function Developer() {
  const [state, setState] = useState<DeveloperState | null>(null), [busy, setBusy] = useState(false), [notice, setNotice] = useState(''), [error, setError] = useState('')
  const [files, setFiles] = useState<File[]>([]), [slug, setSlug] = useState(''), [categoryName, setCategoryName] = useState(''), [categoryDescription, setCategoryDescription] = useState('')
  const load = async () => { const response = await fetch('/__developer/state'); if (!response.ok) throw new Error('Developer server is unavailable. Run npm run dev.'); setState(await response.json() as DeveloperState) }
  useEffect(() => { void load().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Could not load developer mode.')) }, [])
  const run = async (action: () => Promise<unknown>, message: string) => { setBusy(true); setError(''); setNotice(''); try { await action(); await load(); setNotice(message) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Action failed.') } finally { setBusy(false) } }
  const importFolder = (event: FormEvent) => { event.preventDefault(); void run(async () => { const rootName = files[0]?.webkitRelativePath.split('/')[0] ?? ''; const uploads = await Promise.all(files.map(async (file) => ({ path: file.webkitRelativePath.split('/').slice(rootName ? 1 : 0).join('/') || file.name, data: await fileBase64(file) }))); await post('import', { slug, files: uploads }); setFiles([]); setSlug('') }, 'Article imported and content rebuilt. Reload the site to see it.') }
  const addCategory = (event: FormEvent) => { event.preventDefault(); void run(() => post('category', { operation: 'add', name: categoryName, description: categoryDescription }), 'Category added.').then(() => { setCategoryName(''); setCategoryDescription('') }) }
  const renameCategory = (name: string) => { const nextName = window.prompt('New category name', name); if (nextName && nextName !== name) void run(() => post('category', { operation: 'rename', name, nextName }), `Renamed ${name}. Existing articles were updated.`) }
  const deleteCategory = (name: string) => { if (window.confirm(`Delete “${name}”? Articles using it will become Uncategorized.`)) void run(() => post('category', { operation: 'delete', name }), `Deleted ${name}.`) }
  const uploadBackground = (file?: File) => { if (file) void run(async () => post('background', { operation: 'upload', name: file.name, data: await fileBase64(file) }), 'Background uploaded and selected.') }
  const updateSite = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void run(() => post('site', { title: form.get('title'), description: form.get('description') }), 'Homepage title and description updated.') }

  return <section className="page developer"><div className="developer-heading"><div><p className="eyebrow">LOCAL TOOLS</p><h1>Developer mode.</h1><p className="intro">Manage the library without editing configuration files. This page exists only while the Vite development server is running.</p></div><div className="dev-stat"><strong>{state?.articleCount ?? '—'}</strong><span>article folders</span></div></div>{error && <div className="dev-message error" role="alert">{error}</div>}{notice && <div className="dev-message" role="status">{notice}</div>}<div className="developer-grid">
    {state && <section className="dev-panel"><PanelTitle icon={<RefreshCw />} title="Homepage identity" text="Change the public title and introductory description." /><form onSubmit={updateSite}><label className="field">Website title<input name="title" required maxLength={80} defaultValue={state.siteTitle} /></label><label className="field">Homepage description<textarea name="description" required maxLength={300} rows={4} defaultValue={state.siteDescription} /></label><button className="dev-button" disabled={busy}>Save homepage text</button></form></section>}
    <section className="dev-panel"><PanelTitle icon={<FolderUp />} title="Import an article" text="Select a folder with one Markdown file and optional local media." /><form onSubmit={importFolder}><label className="field">Article slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={(event) => setSlug(event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '-'))} placeholder="my-new-article" /></label><label className="folder-picker"><FolderUp /><span>{files.length ? `${files.length} files selected` : 'Choose article folder'}</span><input required type="file" multiple {...{ webkitdirectory: '' }} onChange={(event) => { const selected = Array.from(event.target.files ?? []); setFiles(selected); if (!slug && selected[0]) setSlug(selected[0].webkitRelativePath.split('/')[0].toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')) }} /></label><button className="dev-button" disabled={busy || !files.length}><Plus /> Import and validate</button></form></section>
    <section className="dev-panel"><PanelTitle icon={<Plus />} title="Categories" text="Add, rename, or delete editorial subjects." /><form className="category-form" onSubmit={addCategory}><input required value={categoryName} onChange={(event) => setCategoryName(event.target.value)} placeholder="Category name" /><input value={categoryDescription} onChange={(event) => setCategoryDescription(event.target.value)} placeholder="Short description (optional)" /><button className="dev-button" disabled={busy}><Plus /> Add</button></form><div className="category-list">{state?.categories.map((category) => <div key={category.name}><span><b>{category.name}</b><small>{category.description || 'No description'}</small></span><button onClick={() => renameCategory(category.name)}>Rename</button><button className="danger" onClick={() => deleteCategory(category.name)} aria-label={`Delete ${category.name}`}><Trash2 /></button></div>)}</div></section>
    <section className="dev-panel backgrounds"><PanelTitle icon={<ImagePlus />} title="Homepage background" text="Images are stored in public/background/." /><label className="folder-picker"><ImagePlus /><span>Upload background image</span><input type="file" accept="image/png,image/jpeg,image/webp,image/avif,image/gif,image/svg+xml" onChange={(event) => uploadBackground(event.target.files?.[0])} /></label><div className="background-list">{state?.backgrounds.map((path) => <div className={state.background === path ? 'selected' : ''} key={path}><img src={path} alt="" /><span>{path.split('/').pop()}</span><button onClick={() => void run(() => post('background', { operation: 'select', path }), 'Background selected.')}>Use</button><button className="danger" onClick={() => void run(() => post('background', { operation: 'delete', path }), 'Background deleted.')}><Trash2 /></button></div>)}</div><button className="secondary-button" disabled={busy || !state?.background} onClick={() => void run(() => post('background', { operation: 'reset' }), 'Background reset to default.')}><RotateCcw /> Reset background</button></section>
    <section className="dev-panel dev-actions"><PanelTitle icon={<RefreshCw />} title="Maintenance" text="Revalidate Markdown and refresh generated JSON." /><button className="dev-button" disabled={busy} onClick={() => void run(() => post('rebuild'), 'All content validated and rebuilt.')}><RefreshCw className={busy ? 'spin' : ''} /> Rebuild content</button><button className="secondary-button" onClick={() => location.reload()}><RefreshCw /> Apply changes and reload</button></section>
  </div></section>
}

function PanelTitle({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="dev-panel-title">{icon}<div><h2>{title}</h2><p>{text}</p></div></div> }
