import { useEffect, useState } from 'react'
import { Menu, Moon, Palette, Sun, X } from 'lucide-react'
import { Link, NavLink } from 'react-router-dom'
export type WebsiteStyle = 'editorial' | 'reading' | 'geek' | 'minimal'
export type FontChoice = 'system' | 'serif' | 'humanist' | 'mono' | 'classic'
export type FontSize = 'small' | 'medium' | 'large'
const styleLabels: Record<WebsiteStyle, string> = { editorial: 'Editorial', reading: 'Reading', geek: 'Geek', minimal: 'Minimal' }
const fontLabels: Record<FontChoice, string> = { system: 'System', serif: 'Serif', humanist: 'Humanist', mono: 'Mono', classic: 'Classic' }
const sizeLabels: Record<FontSize, string> = { small: 'Small', medium: 'Medium', large: 'Large' }
export default function Header({ theme, setTheme, websiteStyle, setWebsiteStyle, fontChoice, setFontChoice, fontSize, setFontSize }: { theme: string; setTheme: (theme: string) => void; websiteStyle: WebsiteStyle; setWebsiteStyle: (style: WebsiteStyle) => void; fontChoice: FontChoice; setFontChoice: (font: FontChoice) => void; fontSize: FontSize; setFontSize: (size: FontSize) => void }) { const [scrolled, setScrolled] = useState(false), [open, setOpen] = useState(false); useEffect(() => { const update = () => setScrolled(scrollY > 24); addEventListener('scroll', update, { passive: true }); return () => removeEventListener('scroll', update) }, []); const links = [['/', 'Home'], ['/explore', 'Explore'], ['/timeline', 'Timeline'], ['/about', 'About']]; return <header className={scrolled ? 'header scrolled' : 'header'}><Link to="/" className="brand">R.</Link><nav className={open ? 'nav open' : 'nav'}>{links.map(([to, name]) => <NavLink key={to} to={to} onClick={() => setOpen(false)}>{name}</NavLink>)}</nav><div className="header-actions"><label className="style-switch" title="Website style"><Palette /><span className="sr-only">Website style</span><select value={websiteStyle} onChange={(event) => setWebsiteStyle(event.target.value as WebsiteStyle)}>{Object.entries(styleLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="font-switch" title="Reading font"><span aria-hidden="true">Aa</span><span className="sr-only">Reading font</span><select value={fontChoice} onChange={(event) => setFontChoice(event.target.value as FontChoice)}>{Object.entries(fontLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="font-switch" title="Text size"><span aria-hidden="true">A</span><span className="sr-only">Text size</span><select value={fontSize} onChange={(event) => setFontSize(event.target.value as FontSize)}>{Object.entries(sizeLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><button className="icon-btn" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label="Toggle color theme">{theme === 'dark' ? <Sun /> : <Moon />}</button><button className="icon-btn menu" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button></div></header> }
